### ISSUE TITLE
Cannot start php-fpm, configuration error

### ISSUE THREAD

**Issue by david-torres** [mayflower/puppet-php#100]
After installing the latest version of this module (3.3.0) I ran into a problem where php-fpm would no longer start. 

    $ sudo php5-fpm -c /etc/php5/fpm/php-fpm.conf
    [19-Jul-2015 22:56:44] ERROR: [/etc/php5/fpm/php-fpm.conf:118] unknown entry 'systemd_interval'
    [19-Jul-2015 22:56:44] ERROR: failed to load configuration file '/etc/php5/fpm/php-fpm.conf'
    [19-Jul-2015 22:56:44] ERROR: FPM initialization failed

Commenting out the line in php-fpm.conf fixes the issue but obviously puppet is going to overwrite this value. I've downgraded to 3.2.2 for now which does not have the problem. Please advise.

puppet-php 3.3.0
Ubuntu 14.04
Puppet 3.4.3
PHP 5.5.27

**Comment by fpletz** [comment]
Thanks for the report. Well, unfortunately php-fpm without systemd support doesn't recognise this configuration option. Fixed in current master and will be released with version 3.3.1 soon.
