### ISSUE TITLE
Include tests execution on README

### ISSUE THREAD

**Issue by stupied4ever** [mayflower/puppet-php#102]
I am working on a feature that I think would be nice to have on the module (related with include on 
pool.conf), but I cant execute the tests. When I run:
`$ bundle exec rspec`
I get the error:
``require': cannot load such file -- test/unit/assertions (LoadError)`

I could see that you want to increase code coverage #99, so, would be nice one explanation on the README
how to execute the tests.

**Comment by stupied4ever** [comment]
Apparently, the correct way is to run:
`bundle exec rake spec`

am I right?

**Comment by fpletz** [comment]
You may also run
```
bundle exec rake
```
to run all relevant tests.

But you're right, we should really mention this in `README.md`.
