### ISSUE TITLE
extensions specified as a parameter should take precedence over data from hiera.

### ISSUE THREAD

**Issue by alexjfisher** [mayflower/puppet-php#108]
In https://github.com/mayflower/puppet-php/blob/master/manifests/init.pp#L106 $extensions is used if hiera returns no data.  This is the reverse of what normally happens with class parameters.  With all the non-hash paramaters, an automatic hiera lookup is only done when a parameter is not supplied.  I understand that hiera_hash is used for the extensions hash as automatic lookups don't do a deep merge.

I have a situation where I want a one off server to be configured with just a few php extensions.  Unfortunately, there are already a larger number of servers that already use the php::extensions hiera key from a defaults.yaml file.  For this one off server, I'd like to be able to ignore the existing hiera data and just pass the extensions as a hash from my profile.  With the current module code, this isn't possible.  I first, thought the fix would be simple.  My botched attempt is here. https://github.com/alexjfisher/puppet-php/commit/f7e6b48ed68c4785e771302005f64a68c7bd85f8

Without changing my existing hiera hierarchy, what could I do?

Perhaps I could add an extra class parameter 'use_hiera' or similar?  For backwards compatibility, it would default to true.  Would such a PR be welcome, or maybe a better solution exists?

Kind Regards,
Alex

**Comment by alexjfisher** [comment]
It might also be worth noting that the settings hash is treated differently.
https://github.com/mayflower/puppet-php/blob/master/manifests/init.pp#L62

If settings is provided, it gets *merged* with whatever is found in hiera.  I probably like this even less, but regardless, I suppose handling of extensions and settings should at least be consistent?

**Comment by globin** [comment]
This is a valid bug, should be handled the same as `$php::settings`, but needs a major release as this potentially breaks stuff for people relying on the current "wrong" behaviour.

**Comment by globin** [comment]
`php::extensions` will now be handled the same as other hash parameters, `deep_merge`'ing them
