### ISSUE TITLE
php5enmod in php5.3.10 not available (Ubuntu 12.04)

### ISSUE THREAD

**Issue by fschndr** [mayflower/puppet-php#112]
"php5enmod was introduced in Debian in version 5.4.0~rc6-2 of the package php5" [fkraiem at askubuntu.com](http://askubuntu.com/questions/495920/php5enmod-returns-command-not-found)

The exec of php5enmod in [extensions.pp](https://github.com/mayflower/puppet-php/blob/master/manifests/extension.pp#L182) could be bypassed for php5.3.10 installations. Since 5.3.10 is the default apt package version for php in Ubuntu 12.04, we got an "Could not find command '/usr/sbin/php5enmod'" when installing modules. 

Is there a clean way to get the installed version of php from within your module as bypass condition? 
Other (dirty) workarounds to find an bypass condition could be to `which php5enmod` or grep in `php -v`.

Thank you,

Fabian

**Comment by globin** [comment]
We removed PHP 5.3 support intentionally to make people use a supported PHP version (#44). Please upgrade to a newer version to receive security fixes and not be attackable. This module should have everything in place to do this from the ops side and if something is missing or needs fixing we'll be happy to assist.
