### ISSUE TITLE
Multiple versions at once

### ISSUE THREAD

**Issue by Ulrar** [mayflower/puppet-php#114]
Hi,

Not really an issue, just a question.
Might have missed it, but I don't see a way to install and manage multiple versions of PHP at the same time on a single node ? The module looks like it would perfectly fit our needs otherwise.
One of the big advantage of fpm being that you can have multiple versions on the same server, at least for us. Is there a way to do it, or is it planned to add it someday ?

Thanks !

**Comment by fadenb** [comment]
Hi @Ulrar,

at the moment it is not possible to manage multiple versions of PHP at the same time using this Puppet module nor it is planned anytime soon.

Feel free to implement this feature but I can not guarantee that it will ever be incorporated into the module as it is not the most common use-case.

**Comment by fpletz** [comment]
This is actually quite difficult because we try to wrap standard distribution packages.

My suggestion would be to use different VMs or containers for different PHP versions and either use a HTTP frontend proxy that connects to HTTP servers on the VMs or let php-fpm listen to an internal IP and connect from the frontend HTTP server with fastcgi.

**Comment by Ulrar** [comment]
Well that doesn't fit our use case at all, since we manage client's server.
We can't really ask them to dedicate other servers just for that.
I guess we'll keep the current method, downloading the sources on the
server and compile each version by hand, which works pretty well. Just
wondered if there was a way to handle that via puppet, but no big deal.

Thanks for the answers !

2015-08-28 15:30 GMT+02:00 Franz Pletz <notifications@github.com>:

> This is actually quite difficult because we try to wrap standard
> distribution packages.
>
> My suggestion would be to use different VMs or containers for different
> PHP versions and either use a HTTP frontend proxy that connects to HTTP
> servers on the VMs or let php-fpm listen to an internal IP and connect from
> the frontend HTTP server with fastcgi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mayflower/puppet-php/issues/114#issuecomment-135775877>
> .
>



-- 
Kévin Lemonnier

**Comment by fpletz** [comment]
Well, if it's a Linux machine you could just create containers with LXC. This doesn't add too much overhead. But you would have do dig into LXC first. :)

**Comment by Ulrar** [comment]
And have a different puppet per LXC container ?
Seems like a lot, compiling the multiple versions by hand is easier.
I guess I might use the module for the "main" version, and when needed just
add other versions by hand as usual. We don't have that much servers where
multiple versions are needed, and it's usually not needed for long (just
the time to migrate the code to the new version) so it'll be okay.

Thanks anyway !

2015-08-28 15:37 GMT+02:00 Franz Pletz <notifications@github.com>:

> Well, if it's a Linux machine you could just create containers with LXC.
> This doesn't add too much overhead. But you would have do dig into LXC
> first. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mayflower/puppet-php/issues/114#issuecomment-135777366>
> .
>



-- 
Kévin Lemonnier

**Comment by arunbatar** [comment]
You can have one puppet file per PHP version and apply them one at a time.

**Comment by mnsmithuk** [comment]
Did anyone have a workaround on how to make this module work for multiple versions or know of a different module that can achieve this.  Looks like it would be a lot of work to fork and add the functionality.
