### ISSUE TITLE
Can we make ::php::extension public (part of the module API)?

### ISSUE THREAD

**Issue by mpdude** [mayflower/puppet-php#126]
The extension.pp class emits a warning saying that it is private.

So, what is the recommended way to add a particular extension only for a subset of nodes?

I am following the recommendations to build a "roles and profiles"-style configuration (http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-2/) and using hiera for selecting the classes per node is a discouraged practice.

**Comment by fpletz** [comment]
You're absolutely right, `::php::extension` should indeed be public, you can use it as a resource in in your manifests. We use hiera with deep merging to install extensions with the `php::extensions` hash.

There's already #118. If you like, you can just submit a PR that removes that warning.

**Comment by mpdude** [comment]
See #127.

**Comment by fpletz** [comment]
Closed by #127. Thanks!
