### ISSUE TITLE
Switch to use "ensure_packages" to avoid duplicate declarations

### ISSUE THREAD

**Issue by minorOffense** [mayflower/puppet-php#133]
Some modules declare dependencies which this module is using as well. Using the puppetlabs stdlib function 'ensure_packages' reduces the chance of duplicate declarations. 

Ex:
````puppet
      package { $real_package:
       	ensure   => $ensure,
       	provider => $provider,
       	source   => $real_source,
       	require  => [
          Class['::php::pear'],
          Class['::php::dev'],
       	],
      }
````
and instead
````puppet
ensure_packages($real_package, {ensure=> $ensure, provider => $provider ...})
````

Something like that.

**Comment by fpletz** [comment]
That makes sense. Thanks for the suggestion!

**Comment by fpletz** [comment]
On second thought and looking at all occurrences, all of the uses of explicit package resources are for packages that should only be managed by the puppet module itself. For dependencies of modules we're already using `ensure_resources('package', $header_packages)`.

Your example above is from `manifests/extension.pp` which is specifically for pecl extensions that are even prefixed with `'pecl-'`, so there shouldn't really be any clashes in my opinion. What do you think?

**Comment by minorOffense** [comment]
But there are instances where another module may also declare that dependency. Whether it *should* be managed by this or not. Other modules may say "I need this and I'm going to ensure it's there". Which will cause the duplicate declaration.

This doesn't change the php module from managing the library, it just makes sure that if another module is present that doesn't strictly depend on mayflower/php and wants to ensure the same package is present that you don't get a conflict.

**Comment by globin** [comment]
Yeah but we already do that for all normal packages?
Can you point us to the exact location or paste your error message?

**Comment by mmoll** [comment]
@minorOffense what's the status here?

**Comment by minorOffense** [comment]
It's the "duplicate declaration" error. Have a look at the https://github.com/tPl0ch/puppet-composer or any other PHP module. Having php composer enabled in this module shouldn't break another module's capacity to declare it needs that package as well.

**Comment by mmoll** [comment]
to quote @globin: " Can you point us to the exact location or paste your error message?"

**Comment by mmoll** [comment]
as an interesting side note, there's a difference between `present` and `installed`: https://github.com/theforeman/puppet-dns/pull/61#issuecomment-225166980
Anyway, closing, as there was no reaction.
