### ISSUE TITLE
phpversion fact calls "php -v" without checking if php is installed

### ISSUE THREAD

**Issue by spotzero** [mayflower/puppet-php#134]
On the first puppet run, I get the following error:
Could not retrieve fact='phpversion', resolution='<anonymous>': private method `split' called for nil:NilClass

It looks like the reason is that the phpversion fact tries to run "php -v" without checking if php is present.

**Comment by fpletz** [comment]
I don't see this error message. What version of Puppet and Ruby are you using?

**Comment by fpletz** [comment]
I was able to reproduce this and fixes this on master.
