### ISSUE TITLE
PHP settings not change correctly

### ISSUE THREAD

**Issue by pimjansen** [mayflower/puppet-php#135]
By default the php.ini value of the always_populate_raw_post_data is set to -1 but the value is disabled: `#always_populate_raw_post_data = -1`

I am unable to enable the setting since i cannot update the key.
```
class { 'php':
  settings => {
    'Date/date.timezone' => 'Europe/Amsterdam',
    'always_populate_raw_post_data' => '-1',
  }
}
```

**Comment by fpletz** [comment]
The setting `always_populate_raw_post_data` is in the inifile section `PHP` of `php.ini`, so you have to use the key `PHP/always_populate_raw_post_data`. I've just tested this and it works for me like this.

**Comment by mmoll** [comment]
@pimjansen ping?

**Comment by pimjansen** [comment]
@mmoll ping?!

I stopped using this module since i couldnt get it to work with PHP7. So i did not test it but if you tell me it will work like that, i trust you on your blue blue eyes :)

**Comment by mmoll** [comment]
@pimjansen OK, sorry to hear that, with the current master it should be easier to get PHP7 with just some parameters, but as fpletz tested, I'm closing this issue now. :clock12:
