### ISSUE TITLE
Pear versioning error when attempting to install DB

### ISSUE THREAD

**Issue by bobweston** [mayflower/puppet-php#136]
I'm running this module on ubuntu 14.04 with puppet 3.8.3. When attempting to install DB via pear, I get the following error:

Error: /usr/bin/pear install DB returned 1 instead of one of [0]
Error: /Stage[main]/Projects::Interact::Servers::App::Php/Exec[pear install DB]/returns: change from notrun to 0 failed: /usr/bin/pear install DB returned 1 instead of one of [0]

I tried running the command manually in my vm, and got this error indicating that the version of pear used is out of date:

sudo pear install DB.

This results in the following warning and error:

WARNING: "pear/DB" is deprecated in favor of "pear/MDB2"
pear/DB requires package "pear/PEAR" (version >= 1.10.0), installed version is 1.9.5
No valid packages found
install failed

Any thoughts or advice on a work around would be appreciated.

I should add that 1.9.5 seems to be the latest version available on ubuntu 14.04.

-Bob

**Comment by fpletz** [comment]
Sorry, but I think this problem is out of scope for this module to fix.

I guess the easiest thing to do would to use an older version, like 1.9.0 (see https://pear.php.net/package/DB/download/1.9.0) as this dependency was introduced in 1.9.1 and the latest version is 1.9.2.

**Comment by karimhb** [comment]
No need to install an older version of DB. Simply run the command below and pear will update itself. Then install DB.
    pear install pear

**Comment by Marietto76** [comment]
thanks @karimhb !  i was searching in a million of post how to install only pear DB but always it redirect to insall MDB2.

**Comment by kazitanvirahsan** [comment]
Thank you @karimhb

**Comment by gman1820** [comment]
my solution was to use the --force

yum -y install php-dba
pear install pear
pear install --force DB

**Comment by Pearlien-Batz** [comment]
> my solution was to use the --force
> 
> yum -y install php-dba
> pear install pear
> pear install --force DB

Thanks gman1820, worked perfectly.
