### ISSUE TITLE
Service refresh all the time

### ISSUE THREAD

**Issue by frankvolkel** [mayflower/puppet-php#158]
With some extensions, a service refresh seems to be called every time puppet agent is run. This can be disruptive in production systems. 

```Info: Php::Extension[mysql]: Scheduling refresh of Service[php-fpm]```

My hiera definition for extensions: 
```php::extensions:
  json: 
    provider: pecl
  pgsql: {}
  mysql: {}
  gd: {}
  xml: {}
  soap: {}
  mbstring: {}
  mcrypt: {}
  apc:
    package_prefix: php-pecl-
    settings:
      apc.stat: 1
      apc.stat_ctime: 1```

**Comment by jg-development** [comment]
The service refreshment of the mcrypt module is always triggered for me too:

aaa@xxx:/etc/puppet$ sudo /usr/sbin/php5enmod mcrypt
WARNING: Not enabling the mcrypt module for cli SAPI since module symlink
WARNING: already exists in /etc/php5/cli/conf.d with different content.
WARNING: Not enabling the mcrypt module for apache2 SAPI since module symlink
WARNING: already exists in /etc/php5/apache2/conf.d with different content.
WARNING: Not enabling the mcrypt module for fpm SAPI since module symlink
WARNING: already exists in /etc/php5/fpm/conf.d with different content.

**Comment by globin** [comment]
Could you give more information on the system you are using this module on?

**Comment by jg-development** [comment]
It is a standard vagrant box with ubuntu trusty 14.04

**Comment by ian-d** [comment]
This is also happening here with the apc module, which mean every puppet run the php-fpm pool gets restarted (and so does the APC cache!). We're on CentOS Linux release 7.2.1511 (Core).

Every puppet run:
```
Notice: /Stage[main]/Php/Php::Extension[apc]/Package[pecl-apc]/ensure: created
Info: Php::Extension[apc]: Scheduling refresh of Service[php-fpm]
Notice: /Stage[main]/Php::Fpm::Service/Service[php-fpm]: Triggered 'refresh' from 1 events
```

```
class { 'php':
    extensions => { 'json'     => {},
                    'mysql'    => {},
                    'redis'    => {},
                    'gd'       => {},
                    'mbstring' => {},
                    'pear-CAS' => {},
                    'apc'      => {
                                    provider => 'pecl',
                                    settings => {
                                        'apc.stat'       => '1',
                                        'apc.stat_ctime' => '1',
                                    },
                                  },
                  },
    require    => Class['apache'],
  }
```

**Comment by ian-d** [comment]
Nevermind, my fault. I was using v3.4.2, instead of the current master branch. My problem was fixed by PR #144.

**Comment by igalic** [comment]
so we should have a fresh release then.

**Comment by fpletz** [comment]
Thanks for testing with the current master and your feedback. Closing this now because we're about to release 4.0.0. Sorry for the long wait.
