### ISSUE TITLE
How to change default pool settings in php::fpm without Hiera?

### ISSUE THREAD

**Issue by antaflos** [mayflower/puppet-php#160]
Most parameters of the private class `php::fpm` are not exposed through the `php` class (init.pp) so without Data Binding and Hiera there is no way to change things like `$settings` or `$pools` in `php::fpm`.

I think the parameters of the main `php` class should be extended to expose the parameters of the classes it wraps, so they, too can be set when declaring the `php` class.

Coincidentally the new PR #159 touches on this very issue.

**Comment by mmoll** [comment]
@antaflos care to send a PR for the params you need exposed?

**Comment by antaflos** [comment]
@mmoll Will do!

**Comment by mmoll** [comment]
closing this for now and awaiting the PR. :cake:

**Comment by antaflos** [comment]
@mmoll I am currently working on this but I am not a fan of having so many classes that take parameters. As `php::fpm` is currently implemented we have `php::fpm`, `php::fpm::config` and `php::fpm::service` which are all parametrised classes, as well as the main class `php` (init.pp). In addition we have several places where parameters can be set via explicit `hiera_hash()` calls.

This is a bit of a nightmare to maintain or even use.

I am inclined to refactor all of `php::fpm` to try and reduce this complexity but this will most certainly not be backwards compatible all the way.

What do you think?

**Comment by mmoll** [comment]
The situation is a bit complicated, as the maintainers of this module at mayflower are using mainly NixOS now and I'm not using this module... @fpletz, @fadenb and @globin would be the best people to ask

**Comment by fpletz** [comment]
Also see #151. This module was not intended to be used without hiera for advanced configurations. A major refactoring is indeed needed.

**Comment by igalic** [comment]
i'm still using this module… on ubuntu though (mostly 14.04, and soon 16.04)
i'd love to help out. especially considering that this module is officially endorsed by puppetlabs as "approved" https://forge.puppetlabs.com/mayflower/php

**Comment by mmoll** [comment]
see https://github.com/mayflower/puppet-php/issues/168#issuecomment-200465664
