### ISSUE TITLE
Is it possible to manage configs only?

### ISSUE THREAD

**Issue by pashamesh** [mayflower/puppet-php#164]
I'm using custom compiled php in `/opt`. I want to manage it's configs without packages managing. Is it possible?

I tried to set `ensure: held` but still it install packages.

OS: ubuntu-server-14.04
Puppet: 4.3.2

**Comment by pashamesh** [comment]
Looks like: `ensure: asbsent` can help. Is it correct?

**Comment by mmoll** [comment]
Using this module without managing packages is not really its intended use case, but if you know what you are doing by setting the respective OS packages to absent, that might indeed work for your case.
