### ISSUE TITLE
Hiera php::config::settings not modiying /etc/php.ini

### ISSUE THREAD

**Issue by centric-jim** [mayflower/puppet-php#176]
I hope I'm just being stupid, but setting hiera values for php::config::settings: is not modifying /etc/php.ini.  If this is not the correct way to set/modify /etc/php.ini, the please let me know the correct way or update README.md.  I could not understand in the manifest files nor README.md for how do achieve this.  

If I declare values for 'php::cli::settings', then /etc/php-cli.ini gets modified correctly.  For example, here's excerpts from my host.yaml file -- (some formatting/spacing is lost in this post)

---
 classes:
    - apache
 apache::default_confd_files: false
 apache::default_mods: false
 apache::default_vhost: false
 apache::server_tokens: ProductOnly
 apache::server_signature: 'Off'
 apache::trace_enable: 'Off'
 apache::mpm_module: prefork
 apache::mod::prefork::startservers: 8
 apache::mod::prefork::minspareservers: 5
 apache::mod::prefork::maxspareservers: 20
 apache::mod::prefork::serverlimit: 1024
 apache::mod::prefork::maxclients: 1024
 apache::mod::prefork::maxrequestsperchild: 2000
 
 # php::config::settings:
 # php::cli::settings:
 # php::global::settings:
 php::global:
    PHP/engine: 'On'
    PHP/short_open_tag: 'On'
    PHP/aps_tags: 'Off'
    PHP/precision: 14
    PHP/output_buffering: 4096
    PHP/zlib.output_compressionr: 'Off'
    PHP/implicit_flush: 'Off'
    PHP/serialize_precision: 100
    PHP/zend.enable_gc: 'On'
    PHP/expose_php: 'Off'
    PHP/max_execution_time: '300'

**Comment by Tamerz** [comment]
I appear to be having the same issue. Also, php.ini doesn't seem to get touched at all, even if I directly add the settings in the manifest instead of hiera.

**Comment by mmoll** [comment]
Is this with 3.4.2 or the current master branch? Note that some parameters are different between these versions.

**Comment by centric-jim** [comment]
We look to be running 3.4.2 --- 
From CHANGELOG.md
## 3.4.2
 * Fix a bug that changed the default of `php::manage_repos` to `false` on
   Debian-based operating systems except wheezy. It should be turned on by
   default. (#116)
 * Fix a bug that prevented reloading php-fpm on Ubuntu in some cases.
   (#117, #107)

I see you're up to 4.0.0.  Is the issue addressed in the 4.0.0 version?  If not I was thinking of making a Pull request and adding it in.

p.s. -- Thanks for the response =)

**Comment by mmoll** [comment]
@centric-jim I don't know if it's fixed or not, just wnated to point out that the paramter docs you'll see when reading docs online here on GH already apply only to a later version. If you found a bug and can fix it, please do open a PR :)

**Comment by centric-jim** [comment]
@mmoll -- From what I'm reading, it looks like the module manages config files for phg-cli and php-fpm .. and I'm pretty sure you understand php _way_ better than I do.  We're using mod_php for apache2 and it's getting it's settings, I believe, from /etc/php,ini.  If I should be using php::fpm to manage the config instead of keeping settings in /etc/php.ini then this really isn't an issue.  But If I should be using /etc/php.ini then I'll create a PR and see what I can come up with.

**Comment by Tamerz** [comment]
I just tried today with master branch from GitHub instead of 3.4.2 from Puppet Forge and it works correctly for me. Both using Hiera and directly in the manifest.

**Comment by mmoll** [comment]
seems to be fixed with current master, closing.
