### ISSUE TITLE
How to set php::repo::ubuntu version on local puppet, no hiera, no puppet master

### ISSUE THREAD

**Issue by gesinn-it** [mayflower/puppet-php#185]
I try to setup a simple example with local puppet and the following init.pp, no hiera, no puppet master

```
class { 'php':
  ensure       => latest,
  manage_repos => true,
  fpm          => true,
  dev          => true,
  composer     => true,
  pear         => true,
  phpunit      => false,
}

php::repo::ubuntu {'php56':
  version => '5.6',
}
```

This fails with
`Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type php::repo::ubuntu`

I pull mayflower/puppet-php via librarian with the following Puppetfile:
```
forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'mayflower/php',
  :git => 'https://github.com/mayflower/puppet-php.git',
  :ref => '3.4.1'
```

I'm quite sure I made a stupid "Problem Exists Between Keyboard And Chair" mistake...
Can someone please help me out?

**Comment by alexshepherd-hydrant** [comment]
I don't know if you fixed this already but you're right in thinking it's a pretty simple fix.

You used:

```
php::repo::ubuntu {'php56':
  version => '5.6',
}
```

That means define a resource of type "php::repo::ubuntu" with $title "php56", but if you look in the source, php::repo::ubuntu is a "class" not a "define", which means you'll need to use something like the following (untested):

```
class { 'php::repo::ubuntu':
  version => '5.6'
}
```

However I strongly suggest you integrate Hiera if possible, it won't bite... much ;-)

**Comment by mmoll** [comment]
@alexshepherd-hydrant thanks for clarifiying. Please also have a look what's happening for 4.0 of this module in #190.
