### ISSUE TITLE
test current master on FreeBSD

### ISSUE THREAD

**Issue by mmoll** [mayflower/puppet-php#213]
@fraenki if you have some time in the next weeks, it would be super nice!

**Comment by olevole** [comment]
As minimal action to fix some issue, we need to add FreeBSD empty cases in repo action, #216

**Comment by fraenki** [comment]
No issues for me on FreeBSD with current master. (FreeBSD 10.3, old PHP 5.5)

**Comment by mmoll** [comment]
Danke @fraenki!
