### ISSUE TITLE
remove php::repo::ubuntu::ppa?

### ISSUE THREAD

**Issue by mmoll** [mayflower/puppet-php#214]
@tdm4 mentioned this in #190

**Comment by tdm4** [comment]
@mmoll Probably wouldn't make sense to make this variable configurable, since the choice of PPA depends on the PHP version.

**Comment by mmoll** [comment]
@tdm4 pull requests welcome :)

**Comment by tdm4** [comment]
@mmoll  Pull request #218 for your review 👍
