### ISSUE TITLE
php5-xml is not available in Ubuntu 14.04

### ISSUE THREAD

**Issue by brentclark** [mayflower/puppet-php#230]
Good day

There is a dependency for php5-xml, in the class php::pear.

This package is not available in Ubuntu 14.04.

Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-xml' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php5-xml
Error: /Stage[main]/Php::Pear/Package[php5-xml]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-xml' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php5-xml
Notice: /Package[php-pear]: Dependency Package[php5-xml] has failures: true
Warning: /Package[php-pear]: Skipping because of failed dependencies

apt-cache search php5-xml
php5-xmlrpc - XML-RPC module for php5

apt-cache search php-xml 
php-pear - PEAR - PHP Extension and Application Repository
php-xml-dtd - Parsing of DTD files and DTD validation of XML files
php-xml-htmlsax3 - SAX parser for HTML and other badly formed XML documents
php-xml-parser - PHP PEAR module for parsing XML
php-xml-rpc - PHP implementation of the XML-RPC protocol
php-xml-rpc2 - PHP XML-RPC client/server library
php-xml-rss - php based parser for RSS news feeds
php-xml-serializer - swiss-army knife for reading and writing XML files

HTH

Kind Regards
Brent Clark

**Comment by mmoll** [comment]
see discussion in #225
