### ISSUE TITLE
Pecl version can't be set

### ISSUE THREAD

**Issue by justicel** [Mayflower/puppet-php#51]
If you use Hiera with php extensions you can't properly set a version number for an extension, you instead have to manually add the php extension to your manifest with a specific module version. This is due to using the ensure from the main php module. I suggest using a different variable for setting the individual module versions so that it can be pulled in from hiera correctly. I will look at it later if I have time and maybe submit a pull request, but I'm also not sure how you'd best like to solve this so maybe I should wait for a fix from your side.

**Comment by fpletz** [comment]
I think I managed to fix both your problems with those two referenced commits. Are you able to confirm this?
