### ISSUE TITLE
Unable to set extensions as "zend_extension"

### ISSUE THREAD

**Issue by parhamdoustdar** [Mayflower/puppet-php#52]
Currently, it is not possible to change the `extension = ...` line that `puppet-php` inserts into the `extension-name.ini` file. When you want to install something like `xdebug`, for example, you need to change `extension = ...` to `zend_extension = ...`.

I currently override the contents of that file on every provision, but ideally, I'd not want to have to do that.

**Comment by fpletz** [comment]
We should only do this if the extension was installed with pecl. If an extension from an operating system package is loaded the wrong way, please contact your package distributor to fix this.

I've implemented this in #54 which is to be released with 3.0.0 real soon now™.

**Comment by parhamdoustdar** [comment]
Thank you a lot. No, I installed xdebug through pecl.

I'll be eagerly awaiting 3.0!

**Comment by globin** [comment]
3.0 has since been released.
