### ISSUE TITLE
fpm_package_suffix should be just fpm on Red Hat systems

### ISSUE THREAD

**Issue by noodle10000** [Mayflower/puppet-php#55]
Hi,

I noticed that fpm_package_suffix is 'php-fpm' in params.pp when for RHEL based systems (at least mine on RHEL 6.5) it should be just be 'fpm':

    # rpm -qi php-fpm
    Name        : php-fpm                      Relocations: (not relocatable)
    Version     : 5.3.3                             Vendor: Red Hat, Inc.
    Release     : 40.el6_6                      Build Date: Thu 23 Oct 2014 11:06:56 GMT
    Install Date: Thu 15 Jan 2015 17:51:11 GMT      Build Host: x86-022.build.eng.bos.redhat.com
    Group       : Development/Languages         Source RPM: php-5.3.3-40.el6_6.src.rpm
    Size        : 3363344                          License: PHP
    Signature   : RSA/8, Wed 29 Oct 2014 16:25:08 GMT, Key ID 199e2f91fd431d51
    Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
    URL         : http://www.php.net/
    Summary     : PHP FastCGI Process Manager
    Description :
    PHP-FPM (FastCGI Process Manager) is an alternative PHP FastCGI
    implementation with some additional features useful for sites of
    any size, especially busier sites.

Rgds,

Craig.

**Comment by fpletz** [comment]
Thank you very much for reporting this. This was a typo that unfortunately nobody noticed before releasing 3.0. :panda_face: 

I've released 3.0.1 to the forge with the fix:
 * https://forge.puppetlabs.com/mayflower/php
 * https://github.com/Mayflower/puppet-php/releases/tag/3.0.1
