### ISSUE TITLE
customizing pool parameters

### ISSUE THREAD

**Issue by rarutu** [mayflower/puppet-php#65]
hi everyone 

since i am new to puppet i have a hard time understanding what i need to write inside my manifest file in order to change the pool listen parameter to unix:/var/run/php5-fpm.sock, user to nginx and group to nginx?

thanks

**Comment by fpletz** [comment]
We originally intended that you use hiera for creating php-fpm pools. You would basically write this in your hiera config:

```yaml
php::fpm::pools:
  mypool:
    listen: 'unix:/var/run/php5-fpm.sock'
```

You can find out which parameters are supported in our new documention: http://php.puppet.mayflower.de/php/fpm/pool.html

We will have support to create php::fpm::pool resource in the next release. See the linked commit that I pushed to master.
