### ISSUE TITLE
How to switch to PHP5.6 for Dotdeb Debian repository?

### ISSUE THREAD

**Issue by pkordylewski** [Mayflower/puppet-php#66]
Hi,

i'm having a hard time to figure out how to switch to the wheezy-php56 repository. Is this supported?

Cheers,
Patryk

**Comment by fpletz** [comment]
You can find all parameters for configuring Debian repositories here: https://github.com/Mayflower/puppet-php/blob/master/manifests/repo/debian.pp#L32-L36.

In your case. you would just set this in Hiera:
```yaml
php::repo::debian::release: 'wheezy-php56'
```

Unfortunately, we don't have puppetdoc yet, so have too look at the code to find out which parameters are supported. We're working on it. :construction_worker:

**Comment by pkordylewski** [comment]
Thank you for your fast response and your work on this module

**Comment by fpletz** [comment]
@pkordylewski We now have auto-generated documentation over at http://php.puppet.mayflower.de/. Have fun! :beers:
