### ISSUE TITLE
Error installing fpm on ubuntu

### ISSUE THREAD

**Issue by macklus** [mayflower/puppet-php#71]
Hi:

On ubuntu, php5 packages can be installed. As far as i see, problem is puppet try to install "-cli", "-common" packages (forget php5 prefix)

My hiera config:
```
classes:
  - ::php
  - php::cli
  - php::packages
  - php::fpm
php::ensure: latest
php::manage_repos: true
php::fpm: true
php::dev: true
php::composer: true
php::pear: true
php::phpunit: false
php::fpm::config:log_level: notice
php::composer::auto_update: true
```

I solve it change some values. 
Diff is attached

```
diff -r --exclude=.git php/manifests/fpm.pp php-gh/manifests/fpm.pp
13c13
<   $package  = "${php::params::package_prefix}${php::params::fpm_package_suffix}",
---
>   $package  = "${php::package_prefix}${php::params::fpm_package_suffix}",
diff -r --exclude=.git php/manifests/packages.pp php-gh/manifests/packages.pp
18c18
<     $php::params::common_package_suffixes, $php::params::package_prefix
---
>     $php::params::common_package_suffixes, $php::package_prefix
32d31
<  
```

**Comment by fpletz** [comment]
The only class you should have to include is `::php`, so could you try with only this class?

The thing is that as we're referencing parameters from the main class in the `php::fpm` and `php::packages` classes and puppet could evaluate them first, this referencing can fail. Do you get any warnings?

**Comment by macklus** [comment]
My mistake.
In hiera config file, only:
php

is required (no :: before dat)
