### ISSUE TITLE
php-fpm settings through hiera

### ISSUE THREAD

**Issue by rmartinelli** [mayflower/puppet-php#83]
Hi, first of all thanks for the module :)

I had to change this in php/manifests/fpm.pp
-- $real_settings = deep_merge($settings, hiera_hash('::php::fpm::settings', {}))
++ $real_settings = deep_merge($settings, hiera_hash('php::fpm::settings', {}))

in order for this to work through hiera:
php::fpm::settings:
  PHP/max_file_uploads: '4'
  Session/session.cookie_secure: '1'

Is there's something I'm doing wrong?

**Comment by fpletz** [comment]
Thanks for reporting this. I replaced a little bit too much. :cry: 

I fixed this and released 3.2.2 to the forge.
