### ISSUE TITLE
Not able to change listen from 127.0.0.1:9000 to unix:/var/run/php5-fpm.sock

### ISSUE THREAD

**Issue by klub** [mayflower/puppet-php#87]
Not able to change listen from 127.0.0.1:9000 to unix:/var/run/php5-fpm.sock
I have tried 

I tried 
php::fpm::pool::listen: 'unix:/var/run/php5-fpm.sock'

In the hiera yaml file but makes no difference.

**Comment by klub** [comment]
Any feedback please guys?

**Comment by globin** [comment]
Short answer, your direct use case:
```
php::fpm::pools:
    www:
        listen: /var/run/php5-fpm.sock
```

I'm on the road atm, going to push some more docs on configuring pools soon.

(php::fpm::pool is a resource no class => no direct data binding)

**Comment by klub** [comment]
Thank you so much. Thats now worked. Yup definitely some more verbose documentation would be a great help. Thanks again.

**Comment by klub** [comment]
Hi can you show me how to install phing using your module please. Looks like it only enables pear but doesnt let you install phing through it? Is that correct?
