### ISSUE TITLE
Could not find command 'pear'

### ISSUE THREAD

**Issue by arielsalvo** [mayflower/puppet-php#88]
Hi!

I run into this one today.... I didn't  have package php-pear installed 
```
Error: /Stage[main]/Php::Pear/Exec[::php::pear::auto_discover]: Could not evaluate: Could not find command 'pear'
```

Is it this module's responsibility to install it?

**Comment by globin** [comment]
@fpletz wut? (https://github.com/mayflower/puppet-php/blob/master/manifests/pear.pp#L41-L52)

@arielsalvo what is your OS and location of pear when it is installed?

**Comment by arielsalvo** [comment]
Sorry.... vital info left out (my bad ;) )

My OS is Centos 7
```
# which pear
/bin/pear
```

The path seems to be there, but simply installing the package manually fixed the issue.

**Comment by fpletz** [comment]
@arielsalvo What is the name of the package you needed to install to get this working?

**Comment by arielsalvo** [comment]
```
# rpmquery -f /bin/pear
php-pear-1.9.4-21.el7.noarch
```

Came with a bunch of dependencies along with it

**Comment by fpletz** [comment]
Hmm, weird. I don't quite understand how that `exec` can fail because it depends on the package `php-pear`.

Can you please provide some more output from the failing report referring to the php module? For instance, checking if puppet actually installed php-pear would be interesting. And maybe another puppet run with `--debug`.

**Comment by arielsalvo** [comment]
Sorry.... might have been my mistake (I'm only just starting with puppet)

Can't replicate right now so it was either that I run the agent with --noop at the time and the problem stemmed from another missing package that would have been installed in a previous step or that a dependency of php-pear fixed the issue.

I'm leaning for the first one, so we can close this one. If I manage to replicate the issue with the next server I build (pretty soon) I will update.
