### ISSUE TITLE
PECL Extensions which dont work for first time upgrade installation

### ISSUE THREAD

**Issue by snooops** [mayflower/puppet-php#90]
Hi,
pecl upgrade gnupg dont works on a fresh and clean debian 7 machine. but pecl install gnupg does the job. please fix the pecl provider. :)

https://github.com/mayflower/puppet-php/blob/master/lib/puppet/provider/package/pecl.rb

greetings snooops

**Comment by fpletz** [comment]
@snooops Do you have an error message for us? This would help us to understand and reproduce your exact problem.

**Comment by snooops** [comment]
Ok forget it, i just missed a package - blame me
