### ISSUE TITLE
puppetlabs/apt version 1.x dependency conflict

### ISSUE THREAD

**Issue by escalate** [mayflower/puppet-php#92]
Hi everybody!

I'm receiving the following error message during the installation of my required modules with librarian-puppet.

```
[Librarian] Conflict between puppetlabs-apt (~> 1.0) <https://forgeapi.puppetlabs.com> and puppetlabs-apt/2.0.1 <https://github.com/puppetlabs/puppetlabs-apt.git#2.0.1>
Could not resolve the dependencies.
```

I'm already using the APT module in version 2.0.1 in my puppet code.
So librarian-puppet tries to install two different versions of the module and breaks.

Is it possible to change the mayflower/puppet-php dependency for APT module to an newer version e.g 2.x?
Thank you very much!

**Comment by globin** [comment]
Please see note in the fixing commit. We cannot add compatibility for 2.0 and stay compatible with 1.x, so please use >= 2.1. This cannot be defined in the metadata.json due to puppetlabs' crippled semver implementation. :smirk:
