### ISSUE TITLE
php::settings does not allow merging hierarchies

### ISSUE THREAD

**Issue by AlexC** [mayflower/puppet-php#97]
The class "php" does not allow for Hiera data "php::settings" hierarchy merging, due to usage of automatic parameter lookup. Within the "init.pp" file there is the following line, however the variable "$real_settings" is never used.

```
103   # FIXME: for deep merging support we need a explicit hash lookup instead of
104   #        automatic parameter lookup
105   #        (https://tickets.puppetlabs.com/browse/HI-118)
106   $real_settings = hiera_hash('php::settings', $settings)
```

It looks like this needs to be moved just below the "validate_*" function calls, and then pass this variable in instead of "$settings", e.g:

```
 73   if $fpm {
 74     Anchor['php::begin'] ->
 75       class { '::php::fpm':
 76         settings => $real_settings,
 77       } ->
 78     Anchor['php::end']
 79   }
```

**Comment by fpletz** [comment]
Good catch! Thanks for reporting this.

We noticed this issue already but the fix wasn't tested properly so it's still only on my local git repo. We will fix this with the next release which should be ready any day now! :panda_face:

**Comment by AlexC** [comment]
Speedy, thanks @fpletz!
