### ISSUE TITLE
Defining package_name for php packages

### ISSUE THREAD

**Issue by mat1010** [mayflower/puppet-php#98]
Hi, 
is there a way to define a full package name of the php packages?
We are using the IUS repo for the the latest php packages. The default php package is called `php56u` the common package is `php56u-common` is there a way to override the default package name `php` which can only be customized regarding the prefix?

Thanks in advance,
mat1010

**Comment by fpletz** [comment]
Hi @mat1010,
we have exposed the parameter `php::package_prefix`, which can be used to explicitly set a prefix like `"php56u-"` in your case. Depending on your operating system the other package names are derived.

Disregarding extensions, there are exactly three places where we install packages and all can be overridden. First, we have the class `php::packages` which installs the common and cli packages if applicable for your distribution. These are defined in `php::params::common_package_suffixes` or `php::params::common_package_names`. You can override which common packages you want installed by overriding the lists `php::packages::names` and `php::packages::names_to_prefix` (which adds the mentioned prefix to the names).

The other two places are the classes `php::fpm` and `php::dev`. Those classes both have a parameter called `package` that you can use the override the package name of the package that should be installed.

I've looked at the IUS Repo and this hiera data would probably suffice for that repo (sorry, untested).

```yaml
php::package_prefix: php56u-
```

**Comment by mat1010** [comment]
Thanks for you reply  

> `php::package_prefix: php56u-` 

that's what I already did. That works fine and I have to following packages installed
```
php56u-xml-5.6.11-1.ius.centos7.x86_64
php56u-pecl-jsonc-1.3.7-1.ius.centos7.x86_64
php56u-cli-5.6.11-1.ius.centos7.x86_64
php56u-process-5.6.11-1.ius.centos7.x86_64
php56u-pear-1.9.5-1.ius.centos7.noarch
php56u-fpm-5.6.11-1.ius.centos7.x86_64
php56u-common-5.6.11-1.ius.centos7.x86_64
```
But what about the package `php56u.x86_64` ? I don't get it automatically installed by the module :-/

**Comment by globin** [comment]
If you need that package and isn't installed as dependency, this should be what you want:
```
php::packages:
  - php56u
```

**Comment by mat1010** [comment]
Thank you. I played around with
`. 
php::packages:
  - php56u
```
But for some reason it has just no effect. I'll dig deeper into it to find the cause of this strange behaviour.

**Comment by fpletz** [comment]
Well, in that case, please try:
```yaml
php::packages::names:
  - php56u
```

That should do it. :construction_worker:

**Comment by globin** [comment]
whoops, my bad :sob:

**Comment by mat1010** [comment]
Great thanks to both of you. This one did the trick:
```
php::packages::names:
  - php56u
```
